# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x05proto\"[\n\x06\x43lient\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x01(\t\x12\r\n\x05phone\x18\x05 \x01(\t\"1\n\x0f\x43lientsResponse\x12\x1e\n\x07\x63lients\x18\x01 \x03(\x0b\x32\r.proto.Client\"\\\n\x13\x43reateClientRequest\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\x12\r\n\x05phone\x18\x04 \x01(\t\"h\n\x13UpdateClientRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x01(\t\x12\r\n\x05phone\x18\x05 \x01(\t\"!\n\x13\x44\x65leteClientRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xf3\x01\n\rClientService\x12\x39\n\x0c\x43reateClient\x12\x1a.proto.CreateClientRequest\x1a\r.proto.Client\x12\x32\n\nGetClients\x12\x0c.proto.Empty\x1a\x16.proto.ClientsResponse\x12\x39\n\x0cUpdateClient\x12\x1a.proto.UpdateClientRequest\x1a\r.proto.Client\x12\x38\n\x0c\x44\x65leteClient\x12\x1a.proto.DeleteClientRequest\x1a\x0c.proto.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENT']._serialized_start=24
  _globals['_CLIENT']._serialized_end=115
  _globals['_CLIENTSRESPONSE']._serialized_start=117
  _globals['_CLIENTSRESPONSE']._serialized_end=166
  _globals['_CREATECLIENTREQUEST']._serialized_start=168
  _globals['_CREATECLIENTREQUEST']._serialized_end=260
  _globals['_UPDATECLIENTREQUEST']._serialized_start=262
  _globals['_UPDATECLIENTREQUEST']._serialized_end=366
  _globals['_DELETECLIENTREQUEST']._serialized_start=368
  _globals['_DELETECLIENTREQUEST']._serialized_end=401
  _globals['_EMPTY']._serialized_start=403
  _globals['_EMPTY']._serialized_end=410
  _globals['_CLIENTSERVICE']._serialized_start=413
  _globals['_CLIENTSERVICE']._serialized_end=656
# @@protoc_insertion_point(module_scope)
